# This workflow will build a .NET project
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
##
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
 #   - name:  remove files && dirs
 #     run: rm C:\dev\tools\actions-runner\projects\* -r -force -verbose
    - name: run offline
      run: New-Item -Path C:\dev\tools\actions-runner\projects -Name "app_offline.htm" -ItemType "file"
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish insurance
      run: dotnet publish -c Release -o ./publish
    - name: copy app to iis
      run: Copy-Item -Path "C:\dev\tools\actions-runner\_work\dataplus-client\dataplus-client\publish\*" -Destination "C:\dev\tools\actions-runner\projects" -Recurse -Force -verbose
    - name: run online
      run: Remove-Item -Path C:\dev\tools\actions-runner\projects\app_offline.htm
