###### This workflow will build a .NET project###############
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
  
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v3
      
    - name: restore
      run: ./build.ps1 -Restore -Project ${{ vars.CI_SUB_DIR }} ${{ github.head_ref }}.${{ github.sha }}
    - name: build
      run: ./build.ps1 -Build -Configuration TestInstance -Project ${{ vars.CI_SUB_DIR }} ${{ github.head_ref }}.${{ github.sha }}
    - name: publish
      run: ./build.ps1 -Publish -Configuration TestInstance -Project ${{ vars.CI_SUB_DIR }} ${{ github.head_ref }}.${{ github.sha }}
    - name: PreDeploy
      run: | 
        mkdir ${{ vars.CI_COPY_DIR }}\${{ github.head_ref }}.${{ github.sha }}
        Copy-Item -Path ".\${{ github.head_ref }}.${{ github.sha }}\*" -Destination "${{ vars.CI_COPY_DIR }}\${{ github.head_ref }}.${{ github.sha }}" -Recurse -Force -verbose
    - name: Deploy
      run: Start-Process powershell.exe -Verb runAs -ArgumentList "C:\Users\User\actions-runner\_work\dataplus2\dataplus2\build.ps1 -Deploy -Project $false -PhysicalPath C:\Users\User\actions-runner\dataplus-client-publish\${{ github.head_ref }}.${{ github.sha }}"
