# This workflow will build a .NET project
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: usa-action

    steps:
    - uses: actions/checkout@v3
  # # - name: Setup .NET
    #  uses: actions/setup-dotnet@v3
     # with:
      #  dotnet-version: 7.0.203
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish insurance
      run: dotnet publish -c Release -o C:\inetpub\wwwroot\insurance %ComputerName%
    #- name: iis copy project and restart
     # run: |
      ## cp -r  C:\dev\tools\actions-runner\workflow-usa\dataplus-client\dataplus-client\publish\* C:\inetpub\wwwroot\insurance 
       # iisreset %ComputerName% /start
