# This workflow will build a .NET project
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish insurance
      run: dotnet publish -c Release -o ./publish
    - name: copy app to iis
      run: Copy-Item -Path "C:\dev/tools/actions-runner\_work\dataplus-client\dataplus-client\publish\*" -Destination "C:\dev\tools\actions-runner\projects" -Recurse -Force 
    #- name: run scrypt offline
    #  run:  C:\Users\ysunnatov\Desktop\app-restart.ps1
    - name: run scrypt offline
      shell: pwsh
      run: |
        .\app-restart.ps1
