## This workflow will build a .NET project###
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: dataplus-action

    steps:
    - uses: actions/checkout@v3
        
    - name: run restore scrypt
      run: ./build.ps1 -Restore -Project .\DataPlusWeb\Server\DataPlusWeb.Server.csproj
    - name: run build scrypt
      run: ./build.ps1 -Build -Configuration TestInstance -Project .\DataPlusWeb\Server
    - name: run publish scrypt
      run: ./build.ps1 -Publish -Configuration TestInstance -Project .\DataPlusWeb\Server\DataPlusWeb.Server.csproj
    - name: run predeploy scrypt
    - run: ./build.ps1 -PreDeploy -Project $false
#      run: ./build.ps1 -Restore -Configuration TestInstance -Project "src/api.datasub.csproj"
   # - name: set placeholder html
   #   run: New-Item -Path B:\dev\dataplus-client\dataplus-client-publish -Name "app_offline.htm" -ItemType "file"
   # - name: unit test
   #   run: dotnet test --no-build --verbosity normal
   # - name: publish deployment
   #   run: dotnet publish -c Release -o ./publish
   # - name: copy app to iis
   #   run: Copy-Item -Path "B:\dev\dataplus-client\_work\dataplus-client\dataplus-client\publish\*" -Destination "B:\dev\dataplus-client\dataplus-client-publish" -Recurse -Force -verbose
   # - name: remove placeholder html
   #   run: Remove-Item -Path B:\dev\dataplus-client\dataplus-client-publish\app_offline.htm
