# This workflow will build a .NET project
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: usa-action

    steps:
    - uses: actions/checkout@v3
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish insurance
      run: dotnet publish -c Release -o C:\dev\tools\actions-runner\workflow-usa\dataplus-client\dataplus-client\publish
    - name: copy app to iis
      run: Copy-Item -Path C:\dev\tools\actions-runner\workflow-usa\dataplus-client\dataplus-client\publish\*  -Destination C:\inetpub\wwwroot\insurance
    - name: run scrypt offline
      run: ./app_offline.ps1
